<?php
namespace App\Utility\Pool;


use EasySwoole\Component\Pool\PoolObjectInterface;

class RedisPoolObject extends \Redis implements PoolObjectInterface
{
    /**
     * 释放对象时调用
     */
    function gc(){
        $this->close();
    }

    /**
     * 回收对象时调用
     */
    function objectRestore()
    {
        // TODO: Implement objectRestore() method.
    }

    function object($string = '', $key = '')
    {
        parent::object($string, $key); // TODO: Change the autogenerated stub
    }

    /**
     * 每个连接之前会调用 可以判断断线重连
     * @return bool
     */
    function beforeUse(): bool
    {
        // TODO: Implement beforeUse() method.
        return true;
    }
}